-- Add comprehensive AI configuration columns to company_ai_overrides
ALTER TABLE public.company_ai_overrides
ADD COLUMN IF NOT EXISTS primary_model TEXT DEFAULT 'google/gemini-3-pro-preview',
ADD COLUMN IF NOT EXISTS routing_model TEXT DEFAULT 'deepseek-chat',
ADD COLUMN IF NOT EXISTS analysis_model TEXT DEFAULT 'google/gemini-2.5-flash',
ADD COLUMN IF NOT EXISTS voice_model TEXT DEFAULT 'gpt-4o-realtime-preview-2024-12-17',
ADD COLUMN IF NOT EXISTS voice_style TEXT DEFAULT 'alloy',
ADD COLUMN IF NOT EXISTS primary_temperature NUMERIC DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS routing_temperature NUMERIC DEFAULT 0.3,
ADD COLUMN IF NOT EXISTS max_tokens INTEGER DEFAULT 2048,
ADD COLUMN IF NOT EXISTS max_tool_rounds INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS response_length TEXT DEFAULT 'balanced',
ADD COLUMN IF NOT EXISTS response_timeout_seconds INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS fallback_message TEXT DEFAULT 'Thank you for your patience. Someone will respond shortly.',
ADD COLUMN IF NOT EXISTS support_agent_prompt TEXT,
ADD COLUMN IF NOT EXISTS sales_agent_prompt TEXT,
ADD COLUMN IF NOT EXISTS boss_agent_prompt TEXT,
ADD COLUMN IF NOT EXISTS routing_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS routing_confidence_threshold NUMERIC DEFAULT 0.6,
ADD COLUMN IF NOT EXISTS auto_handoff_triggers TEXT[] DEFAULT ARRAY['payment', 'refund', 'lawsuit', 'urgent', 'manager'],
ADD COLUMN IF NOT EXISTS supervisor_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS complexity_threshold INTEGER DEFAULT 50,
ADD COLUMN IF NOT EXISTS enabled_tools TEXT[] DEFAULT ARRAY['create_reservation', 'get_date_info', 'check_availability', 'send_media', 'lookup_product'],
ADD COLUMN IF NOT EXISTS require_confirmation_for TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS quality_scoring_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS auto_flag_threshold INTEGER DEFAULT 70,
ADD COLUMN IF NOT EXISTS content_filtering_level TEXT DEFAULT 'standard',
ADD COLUMN IF NOT EXISTS ab_test_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS ab_test_variant TEXT,
ADD COLUMN IF NOT EXISTS ab_test_model TEXT,
ADD COLUMN IF NOT EXISTS custom_tools JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS response_templates JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS escalation_rules JSONB DEFAULT '[]'::jsonb;